### PR TITLE
HL25 HUD

### PR DESCRIPTION
**Pull request by a1batross**
This set of patches adds support for available since HL25 update HD set of sprite sheets.

Because not every player might like the new HUD look, there is a new cvar `hud_allow_hd` that limits the usage of HD sprites and reverts some style changes, like battery HUD being super close to the left and HUD numbers are shifted down a bit to match the icons (additionally, it fixes HUD inconsistency bug caused by this change, see ValveSoftware/halflife#3728).

There is no way to switch between old and new HUD by toggling `hud_allow_hd` cvar without restarting a level, so I wonder if we should use Xash3D's FCVAR_LATCH extended flag to notify the player that the change will be skipped until server restart.

### CODE REVIEW

**Comment by a1batross** [comment]
I reverse-engineered the exact numbers (like switching between resolutions in `GetSpriteRes` and `iHudNumbersYOffset`) but I wrote the code the way I wanted, so the function I mentioned doesn't exist in decompiled client.so.

**Comment by tmp64** [comment]
While the code matches HL, I think ammo bars should scale with HUD size for consistency

https://github.com/FWGS/hlsdk-portable/blob/e8db2fa3545670c3a0a48a5887215121fa7351ba/cl_dll/ammo.cpp#L328-L337

**Comment by a1batross** [comment]
@tmp64 yeah, I checked that specifically in decompile, and they haven't touched that.
Dunno, it still looks good enough to me.

**Comment by FreeSlave** [comment]
They also got the train sprite wrong as described in https://github.com/ValveSoftware/halflife/issues/3510

**Comment by a1batross** [comment]
@FreeSlave about train code not referencing train sprites hud.txt: I don't think the behavior should be changed that much.

**Comment by a1batross** [comment]
@tmp64 I fixed the ammo bar scaling you mentioned in last commit.

**Comment by FreeSlave** [comment]
Imagine the following situation.
The mod uses this code and provides sprites for high resolutions. Some sprites are larger than 256x256 and the pre-anniversary goldsource wouldn't be able to load them. However the developer wants the mod to work on both current and legacy branches.
So we need to detect whether the client is running on the legacy version, and don't load high res sprites in this case and treat everything as if `hud_allow_hd` was set to 0.

**Comment by a1batross** [comment]
True, that's planned to do.

**Comment by nekonomicon** [comment]
Is it ready to merge?

**Comment by a1batross** [comment]
I'm too lazy to check whether legacy GoldSrc can support this. 

Until we get confirmation that it works, or otherwise I make some detection to disable the HD HUD, I don't think it's ready to be merged.

**Comment by a1batross** [comment]
Also, this:

```
There is no way to switch between old and new HUD by toggling hud_allow_hd cvar without restarting a level, so I wonder if we should use Xash3D's FCVAR_LATCH extended flag to notify the player that the change will be skipped until server restart.
```

I'm still not sure about this. Should we just use LATCH flag from Xash3D (and hope that it won't break anything for GoldSrc) or do some workaround?

**Comment by tmp64** [comment]
BHL does this by checking if one of the new sprites exists  
https://github.com/tmp64/BugfixedHL-Rebased/blob/1a1f601b50217ef8ac5f1d84f7813361c6a36ae1/src/game/client/hud.cpp#L114-L120

**Comment by FreeSlave** [comment]
It's not what I'm talking about.
You can't rely on checking for resources.
Imagine an author wants a mod to run on both steam_legacy and the current HL versions, using benefits of support for highres sprites when it's possible. The old engine doesn't support big sprites (I actually need to check what happens if it tries to do so).

**Comment by nekonomicon** [comment]
>I'm too lazy to check whether legacy GoldSrc can support this.

>Until we get confirmation that it works, or otherwise I make some detection to disable the HD HUD, I don't think it's ready to be merged.

Ok.
Who really need legacy GoldSource support, probably can write version check by yourself.

**Pull request merged**
