### PR TITLE
ARMv8 neon support for studio util

### PR DESCRIPTION
**Pull request by MoeMod**

### CODE REVIEW

**Comment by MoeMod** [comment]
> Does it make any difference?
> 
> Of course, compared with release build.

I found that AngleQuaternion and QuaternionSlerp takes 30%+ cpu time in multiplayer CS, so in such scenario it may save some performance.

**Comment by a1batross** [comment]
It would make sense to add such changes to engine's libpublic as well. And
write tests, so the results are accurate. :).

**Comment by nekonomicon** [comment]
BTW may be use [SSE version](http://gruntthepeon.free.fr/ssemath/sse_mathfun.h)(useful for x86 and e2k) + [SIMD everywhere](https://github.com/simd-everywhere/simde)?
It can give performance boost on many architectures.

**Comment by a1batross** [comment]
@nekonomicon it would be nice to at least start with ARM.

**Review by a1batross — APPROVED** [review]
I mostly approve. Maybe it only needs slight reformatting to be in line with the other SDK code.

Adding a separate SSE variant is out of the scope of this PR.

**Pull request merged**
